name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v1
        with:
            python-version: "3.10"
      - name: Build
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: Install pypa/build
        run: |
          pip install wheel
          pip install build
      - name: Build a wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}
