name: Unittests

on: [push, pull_request]

jobs:
  tests:
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10"]
            os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.python-version }}
      - name: install
        run: |
          pip install .
          pip install pytest
      - name: test
        run: pytest
