#
# This workflow will install the package and run the unittests.
#

name: PyTest tests

on: [push, pull_request]

jobs:

  tests:

    strategy:
      fail-fast: true
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python: "3.13"
          - os: windows-latest
            python: "3.13"

    runs-on: ${{matrix.os}}

    env:
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp/runtime-root"

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python}}

    - run: pip install pytest pytest-cov pytest-qt pyside6
    - run: pip install -e .

    - name: Install Qt system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libegl1 libxkbcommon-x11-0
      # We need quite some packages for `pytest-qt` to run without problems

    - run: pytest --cov=pyqtconsole --cov-report term --cov-report xml

    - name: Upload code coverage
      if: matrix.python == '3.13' && matrix.os == 'ubuntu-latest'
      # Upload needs to be done only once
      uses: coverallsapp/github-action@v2
